#!/bin/bash
#SBATCH -J Peluche
#SBATCH --mem=100gb
#SBATCH --nodes=1
#SBATCH --ntasks=50
#SBATCH --time=03:00:00
#SBATCH --error=error/peluche-ex.e%j
#SBATCH --output=log/peluche-ex.o%j

cd /proj/parkerlab/users/all-ref-aphids

base="/proj/parkerlab/users/all-ref-aphids"

singularity run \
-B /proj/parkerlab/users/all-ref-aphids/lastz-output \
-B /proj/parkerlab/users/all-ref-aphids \
phyluce_1.7.3.sif \
phyluce_probe_slice_sequence_from_genomes \
    --lastz ${base}/lastz-output \
    --conf ${base}/genomic.conf \
    --flank 1000 \
    --name-pattern "aphididae-v2-PRINCIPAL-bait-set.fasta.txt_v_{}.lastz.clean" \
    --output ${base}/extracts
